title: Emīls Stūrītis
description: Embedded Systems and IoT
url: http://EmilsSturitis.github.io
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      author: Emīls Stūrītis